---
deployment:
  tasks:
    # Set the path to your Node.js and npm binaries.
    # This path might vary depending on your hosting setup.
    # Common paths are /home/username/.nvm/versions/node/vX.X.X/bin
    # or you can find it by running `which node` in the cPanel terminal.
    # - export PATH=/home/your_cpanel_username/bin:$PATH

    # Define the deployment path (your public web directory).
    - export DEPLOYPATH=/home/tarpainf/studiomeroclick.com.np/

    # Execute build commands for your React application.
    - /bin/npm install --omit=dev
    - /bin/npm run build
    - /bin/cp -R build/* $DEPLOYPATH
