name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy through SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export PATH=/opt/alt/alt-nodejs18/root/usr/bin:$PATH

            cd /home/tarpainf/repositories/studio_mero_click

            git fetch origin
            git reset --hard origin/main

            npm install
            npm run build

            # Copy production build files into your live domain folder
            rsync -avz --delete dist/ /home/tarpainf/studiomeroclick.com.np/

            # Force restart server
            mkdir -p /home/tarpainf/studiomeroclick.com.np/tmp
            touch /home/tarpainf/studiomeroclick.com.np/tmp/restart.txt